logging:
  level: info
server:
  port: 8080
  context-path: /
spring:
  profiles:
    #active: dev
    include:
      - dev
  devtools:
    restart:
      enabled: true
  output:
    #彩色字体
    ansi:
      enabled: always
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        aop-patterns: org.jypj.dev.service.*
        max-active: 100
        min-idle: 10
        initial-size: 5
        test-on-borrow: true
        validation-query: SELECT 1 FROM DUAL
        max-wait: 60000
        test-on-return: true
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 30000
        remove-abandoned: true
        remove-abandoned-timeout: 1800
        log-abandoned: true
        filters: mergeStat
  aop:
    proxy-target-class: false
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/UserMapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: org.jypj.dev.entity
  #typeEnumsPackage: org.jypj.zgcsx.course.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator:
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: org.jypj.zgcsx.course.config.mybatis.CourseMetaObjectHandler
    #自定义SQL注入器
    #sql-injector:
  configuration:
          map-underscore-to-camel-case: true
          cache-enabled: false